app_controllers:
    name_prefix: app_
    prefix: /{_locale}
    resource: ../../src/Controller/
    type: annotation
    requirements:
        _locale: fr|en


api_controllers:
    name_prefix: api_
    prefix: /api
    resource: ../../src/Controller/Api/
    type: annotation
